define(function () {
	"use strict";

	return [
		"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum turpis libero, blandit ut volutpat vel, volutpat eget magna. Pellentesque purus odio, mollis nec pulvinar vitae, vehicula vitae turpis. In eros tellus, pretium vitae porta sed, ultricies in erat. Quisque mattis semper augue in venenatis. Pellentesque iaculis, lacus non varius ornare, felis tellus convallis mauris, vel aliquam elit nulla eu nisl. Nulla in purus tortor. Etiam euismod faucibus quam, a luctus risus bibendum eu. In id tincidunt lacus. Curabitur tortor risus, sollicitudin ullamcorper vehicula a, convallis non felis. Vestibulum aliquet dapibus erat non consequat. Fusce dignissim mauris ac ante malesuada sollicitudin. Mauris sit amet risus ut metus aliquam sollicitudin. Duis varius lorem eget erat malesuada mattis. Vivamus vehicula magna a mauris euismod nec tempus dolor convallis.",

		"Aliquam ac justo vel orci ornare rutrum. Fusce vitae porta nibh. Praesent non ante at justo egestas pulvinar et ut eros. Suspendisse urna lacus, semper nec malesuada sit amet, gravida quis quam. Nam lectus mauris, eleifend ut venenatis non, commodo ut sapien. Morbi pellentesque tincidunt magna auctor blandit. Cras vel lorem justo.",

		"Fusce feugiat pharetra sem a faucibus. Praesent dictum mauris quis lorem porttitor vel ullamcorper dolor posuere. Ut venenatis, velit eu fermentum gravida, ipsum justo suscipit purus, ac commodo quam est sed sapien. Nullam sed dui sem, vel vestibulum dui. Vivamus felis sem, lacinia tincidunt elementum non, fermentum vel nisl. Nulla tempor purus quis urna varius fermentum. Sed pretium justo ac lectus posuere hendrerit. Suspendisse placerat turpis eget felis eleifend fringilla imperdiet vitae justo. In urna velit, congue nec volutpat non, molestie malesuada libero. Aliquam erat volutpat. Sed euismod tempor justo ac bibendum. Nulla facilisi. Nunc id aliquet orci. Sed id orci et mi laoreet convallis. Praesent sit amet mi vel tortor pretium feugiat. Maecenas purus orci, condimentum sit amet tempus et, porttitor sed nibh.",

		"Duis sodales tempus tortor non adipiscing. Suspendisse pulvinar placerat dictum. Maecenas sed magna elit, eget pharetra lectus. Suspendisse potenti. Maecenas fringilla vulputate leo id porttitor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam tincidunt ultrices nibh id convallis. Nam vestibulum dapibus neque at bibendum. In faucibus ultricies tellus, sed imperdiet lorem egestas nec. Proin ut turpis at metus luctus elementum. Aenean sollicitudin, metus et posuere vehicula, nibh lorem lobortis nisi, a fringilla augue orci nec mi. Aliquam ultricies auctor diam placerat ultricies. Phasellus tempor vehicula est sed tempor.",

		"Duis vitae iaculis lectus. Integer commodo placerat orci, eu consequat lorem suscipit quis. Duis a tellus in felis auctor lobortis ut sed tellus. Fusce diam nisi, pharetra tincidunt molestie vitae, dignissim eu felis. Integer tincidunt dapibus metus, quis faucibus ante hendrerit nec. Praesent feugiat eleifend turpis, et elementum dui tristique nec. Praesent odio leo, ornare in porttitor elementum, varius vel lacus. Fusce aliquet neque quis metus blandit elementum. Aliquam sit amet commodo augue. Praesent aliquet tellus ac lorem accumsan fermentum. Praesent bibendum, mi quis pharetra consectetur, felis eros consequat nunc, a facilisis enim ipsum id tortor. Proin pulvinar convallis pretium. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras rutrum aliquet velit vel consequat.",

		"Ut sed molestie velit. Curabitur vel augue eu est fermentum mollis non imperdiet dui. Nulla blandit vulputate suscipit. Mauris dapibus, leo vitae eleifend pharetra, leo velit condimentum felis, vitae consectetur diam mauris at lorem. Aenean elementum felis sit amet velit cursus semper. Pellentesque tincidunt dapibus cursus. Integer aliquam, enim non elementum luctus, mi massa semper urna, nec porttitor felis nunc vitae urna. Donec ultrices ornare neque mollis tempus. Morbi volutpat metus eu mauris condimentum volutpat. Donec nec enim nec dui dapibus sodales. Aliquam consequat fringilla ante, vel eleifend diam tristique fringilla. Quisque euismod, nunc eu pulvinar fringilla, nibh mauris pulvinar nulla, venenatis ullamcorper justo lectus sit amet nibh. Donec congue molestie mi viverra rhoncus."
	];
});
